version: "3.7"

services:
    house_database:
        image: postgres
        container_name: database_housekeeper
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=imperador
            - POSTGRES_PASSWORD=123321
            - POSTGRES_DB=housekeeper
        volumes:
            - pgdata:/data/postgres
    app: 
        build: .
        container_name: housekeeper
        restart: always
        ports: 
            - 3333:3333
        volumes: 
            - .:/usr/app
        links:
            - house_database
        depends_on: 
            - house_database
        
        
volumes:
    pgdata:
        driver: local